struct cmavo_entry cmavo_db[]={
{"a", "A", "sumti or", "logical connective: sumti afterthought or"},
{"a'a", "UI1", "attentive", "attitudinal: attentive - inattentive - avoiding"},
{"a'e", "UI1", "alertness", "attitudinal: alertness - exhaustion"},
{"a'i", "UI1", "effort", "attitudinal: effort - no special effort - repose"},
{"a'o", "UI1", "hope", "attitudinal: hope - despair"},
{"a'u", "UI1", "interest", "attitudinal: interest - disinterest - repulsion"},
{"ai", "UI1", "intent", "attitudinal: intent - indecision - rejection/refusal"},
{"au", "UI1", "desire", "attitudinal: desire - indifference - reluctance"},
{"ba", "PU", "after", "time tense relation/direction: will [selbri]; after [sumti]; default future tense"},
{"ba'a", "UI2", "I anticipate", "evidential: I expect - I experience - I remember"},
{"ba'e", "BAhE", "emphasize next", "forethought emphasis indicator; indicates next word is especially emphasized"},
{"ba'i", "BAI", "replaced by", "basti modal, 1st placereplaced by ..."},
{"ba'u", "UI3", "exaggeration", "discursive: exaggeration - accuracy - understatement"},
{"bai", "BAI", "compelled by", "bapli modal, 1st place (forced by)forcedly; compelled by force ..."},
{"bau", "BAI", "in language", "bangu modal, 1st placein language ..."},
{"be", "BE", "link sumti", "sumti link to attach sumti (default x2) to a selbri; used in descriptions"},
{"be'a", "FAhA1", "north of", "location tense relation/direction; north of"},
{"be'e", "COI", "request to send", "vocative: request to send/speak"},
{"be'i", "BAI", "sent by", "benji modal, 1st place (sender)sent by ..."},
{"be'o", "BEhO", "end linked sumti", "elidable terminator: end linked sumti in specified description"},
{"be'u", "UI5", "lack", "attitudinal modifier: lack/need - presence/satisfaction - satiation"},
{"bei", "BEI", "link more sumti", "separates multiple linked sumti within a selbri; used in descriptions"},
{"bi", "PA1", "8", "digit/number: 8 (digit) [eight]"},
{"bi'e", "BIhE", "hi priority operator", "prefixed to a mex operator to indicate high priority"},
{"bi'i", "BIhI", "unordered interval", "non-logical interval connective: unordered between ... and ..."},
{"bi'o", "BIhI", "ordered interval", "non-logical interval connective: ordered from ... to ..."},
{"bi'u", "UI3a", "new information", "discursive: newly introduced information - previously introduced information"},
{"bo", "BO", "short scope link", "short scope joiner; joins various constructs with shortest scope and right grouping"},
{"boi", "BOI", "end number or lerfu", "elidable terminator: terminate numeral or letteral string"},
{"bu", "BU", "word to lerfu", "convert any single word to BY"},
{"bu'a", "GOhA", "some selbri 1", "logically quantified predicate variable: some selbri 1"},
{"bu'e", "GOhA", "some selbri 2", "logically quantified predicate variable: some selbri 2"},
{"bu'i", "GOhA", "some selbri 3", "logically quantified predicate variable: some selbri 3"},
{"bu'o", "UI7", "start emotion", "attitudinal contour: start emotion - continue emotion - end emotion"},
{"bu'u", "FAhA3", "coincident with", "location tense relation/direction; coincident with/at the same place as; space equivalent of ca"},
{"by", "BY2", "b", "letteral for b"},
{"ca", "PU", "during", "time tense relation/direction: is [selbri]; during/simultaneous with [sumti]; present tense"},
{"ca'a", "CAhA", "actually is", "modal aspect: actuality/ongoing event"},
{"ca'e", "UI2", "I define", "evidential: I define"},
{"ca'i", "BAI", "by authority of", "catni modal, 1st placeby authority of ..."},
{"ca'u", "FAhA2", "in front of", "location tense relation/direction; forwards/to the front of ..."},
{"cai", "CAI", "intense emotion", "attitudinal: strong intensity attitude modifier"},
{"cau", "BAI", "lacked by", "claxu modal, 1st placelacked by ..."},
{"ce", "JOI", "in a set with", "non-logical connective: set link, unordered; \"and also\", but forming a set"},
{"ce'a", "LAU", "font shift", "2-word letteral/shift: the word following indicates a new font (e.g. italics, manuscript)"},
{"ce'e", "CEhE", "afterthought termset", "links terms into an afterthought termset"},
{"ce'i", "PA3", "percent", "digit/number: % percentage symbol, hundredths"},
{"ce'o", "JOI", "in a sequence with", "non-logical connective: ordered sequence link; \"and then\", forming a sequence"},
{"ce'u", "KOhA8", "lambda", "pseudo-quantifier binding a variable within an abstraction that represents an open place"},
{"cei", "CEI", "pro-bridi assign", "selbri variable assignment; assigns broda series pro-bridi to a selbri"},
{"ci", "PA1", "3", "digit/number: 3 (digit) [three]"},
{"ci'e", "BAI", "in system", "ciste modal, 1st place used in scalar negationin system/context ..."},
{"ci'i", "PA5", "infinity", "digit/number: infinity; followed by digits => aleph cardinality"},
{"ci'o", "BAI", "emotionally felt by", "cinmo modal, 1st placeemotionally felt by ..."},
{"ci'u", "BAI", "on the scale", "ckilu modal, 1st placeon the scale ..."},
{"co", "CO", "tanru inversion", "tanru inversion operator; \"... of type ...\"; allows modifier trailing sumti without sumti links"},
{"co'e", "GOhA", "unspecif bridi", "elliptical/unspecified bridi relationship"},
{"co'o", "COI", "partings", "vocative: partings/good-bye"},
{"coi", "COI", "greetings", "vocative: greetings/hello"},
{"cu", "CU", "selbri separator", "elidable marker: separates selbri from preceding sumti, allows preceding terminator elision"},
{"cu'a", "VUhU3", "absolute value", "unary mathematical operator: absolute value/norm|a|"},
{"cu'e", "CUhE", "modal ?", "tense/modal question"},
{"cu'i", "CAI", "neutral emotion", "attitudinal: neutral scalar attitude modifier"},
{"cu'o", "MOI", "probability selbri", "convert number to probability selbri; event x1 has probability (n) of occurring under cond. x2"},
{"cu'u", "BAI", "as said by", "cusku modal, 1st place (attribution/quotation)as said by source ...; used for quotation"},
{"cy", "BY2", "c", "letteral for c"},
{"da", "KOhA1", "something 1", "logically quantified existential pro-sumti: there exists something 1 (usually restricted)"},
{"da'a", "PA4", "all except", "digit/number: all except n; all but n; default 1"},
{"da'e", "KOhA2", "eventual utterance", "pro-sumti: remote future utterance; \"He'll tell you tomorrow. IT will be a doozy.\""},
{"da'i", "UI3", "supposing", "discursive: supposing - in fact"},
{"da'o", "DAhO", "cancel pro-assigns", "discursive: cancel pro-sumti/pro-bridi assignments"},
{"da'u", "KOhA2", "earlier utterance", "pro-sumti: a remote past utterance; \"She couldn't have known that IT would be true.\""},
{"dai", "UI5", "empathy", "attitudinal modifier: marks empathetic use of preceding attitudinal; shows another's feelings"},
{"dau", "PA2", "hex digit A", "digit/number: hex digit A (decimal 10) [ten]"},
{"de", "KOhA1", "something 2", "logically quantified existential pro-sumti: there exists something 2 (usually restricted)"},
{"de'e", "KOhA2", "soon utterance", "pro-sumti: a near future utterance"},
{"de'i", "BAI", "dated", "detri modal, 1st place (for letters)dated ... ; attaches date stamp"},
{"de'o", "VUhU3", "logarithm", "binary mathematical operator: logarithm; [log/ln a to base b]; default base 10 or e"},
{"de'u", "KOhA2", "recent utterance", "pro-sumti: a recent utterance"},
{"dei", "KOhA2", "this utterance", "pro-sumti: this utterance"},
{"di", "KOhA1", "something 3", "logically quantified existential pro-sumti: there exists something 3 (usually restricted)"},
{"di'e", "KOhA2", "next utterance", "pro-sumti: the next utterance"},
{"di'i", "TAhE", "regularly", "tense interval modifier: regularly; subjective tense/modal; defaults as time tense"},
{"di'o", "BAI", "at the locus of", "diklo modal, 1st placeat the locus of ..."},
{"di'u", "KOhA2", "last utterance", "pro-sumti: the last utterance"},
{"do", "KOhA3", "you", "pro-sumti: you listener(s); identified by vocative"},
{"do'a", "UI3", "generously", "discursive: generously - parsimoniously"},
{"do'e", "BAI", "unspecif modal", "elliptical/unspecified modal"},
{"do'i", "KOhA2", "unspecif utterance", "pro-sumti: elliptical/unspecified utterance variable"},
{"do'o", "KOhA3", "you and others", "pro-sumti: you the listener & others unspecified"},
{"do'u", "DOhU", "end vocative", "elidable terminator: end vocative (often elidable)"},
{"doi", "DOI", "vocative marker", "generic vocative marker; identifies intended listener; elidable after COI"},
{"du", "GOhA", "same identity as", "identity selbri; = sign; x1 identically equals x2, x3, etc.; attached sumti refer to same thing"},
{"du'a", "FAhA1", "east of", "location tense relation/direction; east of"},
{"du'e", "PA4", "too many", "digit/number: too many; subjective"},
{"du'i", "BAI", "as much as", "dunli modal, 1st place (equalled by)equally; as much as ..."},
{"du'o", "BAI", "according to", "djuno modal, 1st place (info source)authoritatively; according to ...; known by ..."},
{"du'u", "NU", "bridi abstract", "abstractor: predication/bridi abstractor; x1 is predication [bridi] expressed in sentence x2"},
{"dy", "BY2", "d", "letteral for d"},
{"e", "A", "sumti and", "logical connective: sumti afterthought and"},
{"e'a", "UI1", "permission", "attitudinal: granting permission - prohibiting"},
{"e'e", "UI1", "competence", "attitudinal: competence - incompetence/inability"},
{"e'i", "UI1", "constraint", "attitudinal: feeling constraint - independence - challenge/resistance against constraint"},
{"e'o", "UI1", "request", "attitudinal: request - negative request"},
{"e'u", "UI1", "suggestion", "attitudinal: suggestion - abandon suggest - warning"},
{"ei", "UI1", "obligation", "attitudinal: obligation - freedom"},
{"fa", "FA", "1st sumti place", "sumti place tag: tag 1st sumti place"},
{"fa'a", "FAhA4", "towards point", "location tense relation/direction; arriving at/directly towards ..."},
{"fa'e", "BAI", "reverse of", "fatne modal, 1st placebackwards; reverse of ..."},
{"fa'i", "VUhU2", "reciprocal of", "unary mathematical operator: reciprocal; multiplicative inverse; [1/a]"},
{"fa'o", "FAhO", "end of text", "unconditional end of text; outside regular grammar; used for computer input"},
{"fa'u", "JOI", "and respectively", "non-logical connective: respectively; unmixed ordered distributed association"},
{"fai", "FA", "extra sumti place", "sumti place tag: tag a sumti moved out of numbered place structure; used in modal conversions"},
{"fau", "BAI", "in the event of", "fasnu modal, 1st place (non-causal)in the event of ..."},
{"fe", "FA", "2nd sumti place", "sumti place tag: tag 2nd sumti place"},
{"fe'a", "VUhU3", "nth root of", "binary mathematical operator: nth root of; inverse power [a to the 1/b power]"},
{"fe'e", "FEhE", "space aspects", "mark space interval distributive aspects; labels interval tense modifiers as location-oriented"},
{"fe'i", "VUhU1", "divided by", "n-ary mathematical operator: divided by; division operator; [(((a / b) / c) / ...)]"},
{"fe'o", "COI", "over and out", "vocative: over and out (end discussion)"},
{"fe'u", "FEhU", "end modal selbri", "elidable terminator: end nonce conversion of selbri to modal; usually elidable"},
{"fei", "PA2", "hex digit B", "digit/number: hex digit B (decimal 11) [eleven]"},
{"fi", "FA", "3rd sumti place", "sumti place tag: tag 3rd sumti place"},
{"fi'a", "FA", "sumti place ?", "sumti place tag: place structure number/tag question"},
{"fi'e", "BAI", "created by", "finti modal, 1st place (creator)created by ..."},
{"fi'i", "COI", "hospitality", "vocative: hospitality - inhospitality; you are welcome/ make yourself at home"},
{"fi'o", "FIhO", "selbri to modal", "convert selbri to nonce modal/sumti tag"},
{"fi'u", "PA3", "fraction slash", "digit/number: fraction slash; default \"/n\" => 1/n, \"n/\" => n/1, or \"/\" alone => golden ratio"},
{"fo", "FA", "4th sumti place", "sumti place tag: tag 4th sumti place"},
{"fo'a", "KOhA4", "it-6", "pro-sumti: he/she/it/they #6 (specified by goi)"},
{"fo'e", "KOhA4", "it-7", "pro-sumti: he/she/it/they #7 (specified by goi)"},
{"fo'i", "KOhA4", "it-8", "pro-sumti: he/she/it/they #8 (specified by goi)"},
{"fo'o", "KOhA4", "it-9", "pro-sumti: he/she/it/they #9 (specified by goi)"},
{"fo'u", "KOhA4", "it-10", "pro-sumti: he/she/it/they #10 (specified by goi)"},
{"foi", "FOI", "end composite lerfu", "terminator: end composite lerfu; never elidable"},
{"fu", "FA", "5th sumti place", "sumti place tag: tag 5th sumti place"},
{"fu'a", "FUhA", "reverse Polish", "reverse Polish mathematical expression (mex) operator flag"},
{"fu'e", "FUhE", "indicator scope", "begin indicator long scope"},
{"fu'i", "UI5", "easy", "attitudinal modifier: easy - difficult"},
{"fu'o", "FUhO", "end indicator scope", "end indicator long scope; terminates scope of all active indicators"},
{"fu'u", "VUhU0", "unspecif operator", "n-ary mathematical operator: elliptical/unspecified mathematical expression (mex) operator"},
{"fy", "BY2", "f", "letteral for f"},
{"ga", "GA", "fore or", "logical connective: forethought all but tanru-internal or (with gi)"},
{"ga'a", "BAI", "to observer", "zgana modal, 1st placeto observer ... ; witnessed by ..."},
{"ga'e", "BY1", "upper-case shift", "upper-case letteral shift"},
{"ga'i", "UI5", "hauteur", "attitudinal modifier/honorific: hauteur - equal rank - meekness; used with one of lower rank"},
{"ga'o", "GAhO", "inclusive interval", "closed interval bracket marker; mod. intervals in non-logical connectives; include boundaries"},
{"ga'u", "FAhA2", "above", "location tense relation/direction; upwards/up from ..."},
{"gai", "PA2", "hex digit C", "digit/number: hex digit C (decimal 12) [twelve]"},
{"gau", "BAI", "with active agent", "gasnu modal, 1st place agent/actor case tagwith active agent ..."},
{"ge", "GA", "fore and", "logical connective: forethought all but tanru-internal and (with gi)"},
{"ge'a", "VUhU0", "null operator", "mathematical operator: null mathematical expression (mex) operator (used in >2-ary ops)"},
{"ge'e", "UI6", "unspecif emotion", "attitudinal: elliptical/unspecified/non-specific emotion; no particular feeling"},
{"ge'i", "GA", "fore conn ?", "logical connective: forethought all but tanru-internal connective question (with gi)"},
{"ge'o", "BY1", "Greek shift", "shift letterals to Greek alphabet"},
{"ge'u", "GEhU", "end relative phrase", "elidable terminator: end relative/modal phrases; usually elidable in non-complex phrases"},
{"gei", "VUhU2", "exponential notation", "trinary mathematical operator: order of magnitude/value/base; [b * (c to the a power)]"},
{"gi", "GI", "connective medial", "logical connective: all but tanru-internal forethought connective medial marker"},
{"gi'a", "GIhA", "bridi or", "logical connective: bridi-tail afterthought or"},
{"gi'e", "GIhA", "bridi and", "logical connective: bridi-tail afterthought and"},
{"gi'i", "GIhA", "bridi conn ?", "logical connective: bridi-tail afterthought conn question"},
{"gi'o", "GIhA", "bridi iff", "logical connective: bridi-tail afterthought biconditional/iff/if-and-only-if"},
{"gi'u", "GIhA", "bridi whether", "logical connective: bridi-tail afterthought whether-or-not"},
{"go", "GA", "fore iff", "logical connective: forethought all but tanru internal biconditional/iff/if-and-only-if(with gi)"},
{"go'a", "GOhA", "recent bridi", "pro-bridi: repeats a recent bridi (usually not the last 2)"},
{"go'e", "GOhA", "penultimate bridi", "pro-bridi: repeats the next to last bridi"},
{"go'i", "GOhA", "last bridi", "pro-bridi: preceding bridi; in answer to a yes/no question, repeats the claim, meaning yes"},
{"go'o", "GOhA", "future bridi", "pro-bridi: repeats a future bridi, normally the next one"},
{"go'u", "GOhA", "earlier bridi", "pro-bridi: repeats a remote past bridi"},
{"goi", "GOI", "pro-sumti assign", "sumti assignment; used to define/assign ko'a/fo'a series pro-sumti; Latin 'sive'"},
{"gu", "GA", "fore whether", "logical connective: forethought all but tanru-internal whether-or-not (with gi)"},
{"gu'a", "GUhA", "fore tanru or", "logical connective: tanru-internal forethought or (with gi)"},
{"gu'e", "GUhA", "fore tanru and", "logical connective: tanru-internal forethought and (with gi)"},
{"gu'i", "GUhA", "fore tanru conn ?", "logical connective: tanru-internal forethought question (with gi)"},
{"gu'o", "GUhA", "fore tanru iff", "logical connective: tanru-internal forethought biconditional/iff/if-and-only-if (with gi)"},
{"gu'u", "GUhA", "fore tanru whether", "logical connective: tanru-internal forethought whether-or-not (with gi)"},
{"gy", "BY2", "g", "letteral for g"},
{"i", "I", "sentence link", "sentence link/continuation; continuing sentences on same topic; normally elided for new speakers"},
{"i'a", "UI1", "acceptance", "attitudinal: acceptance - blame"},
{"i'e", "UI1", "approval", "attitudinal: approval - non-approval - disapproval"},
{"i'i", "UI1", "togetherness", "attitudinal: togetherness - privacy"},
{"i'o", "UI1", "appreciation", "attitudinal: appreciation - envy"},
{"i'u", "UI1", "familiarity", "attitudinal: familiarity - mystery"},
{"ia", "UI1", "belief", "attitudinal: belief - skepticism - disbelief"},
{"ie", "UI1", "agreement", "attitudinal: agreement - disagreement"},
{"ii", "UI1", "fear", "attitudinal: fear - security"},
{"io", "UI1", "respect", "attitudinal: respect - disrespect"},
{"iu", "UI1", "love", "attitudinal: love - no love lost - hatred"},
{"ja", "JA", "tanru or", "logical connective: tanru-internal afterthought or"},
{"ja'a", "NA", "bridi affirmer", "bridi logical affirmer; scope is an entire bridi"},
{"ja'e", "BAI", "therefore result", "jalge modal, 1st placeresultingly; therefore result ..."},
{"ja'i", "BAI", "by rule", "javni modal, 1st place (by standard 1)orderly; by rule ..."},
{"ja'o", "UI2", "I conclude", "evidential: I conclude"},
{"jai", "JAI", "modal conversion", "convert tense/modal (tagged) place to 1st place; 1st place moves to extra FA place (fai)"},
{"jau", "PA2", "hex digit D", "digit/number: hex digit D (decimal 13) [thirteen]"},
{"je", "JA", "tanru and", "logical connective: tanru-internal afterthought and"},
{"je'a", "NAhE", "scalar affirmer", "scalar affirmer; denies scalar negation: Indeed!"},
{"je'e", "COI", "roger", "vocative: roger (ack) - negative acknowledge; used to acknowledge offers and thanks"},
{"je'i", "JA", "tanru conn ?", "logical connective: tanru-internal afterthought conn question"},
{"je'o", "BY1", "Hebrew shift", "shift letterals to Hebrew alphabet"},
{"je'u", "UI3", "truth", "discursive: truth - falsity"},
{"jei", "NU", "truth abstract", "abstractor: truth-value abstractor; x1 is truth value of [bridi] under epistemology x2"},
{"ji", "A", "sumti conn ?", "logical connective: sumti afterthought connective question"},
{"ji'a", "UI3b", "in addition", "discursive: additionally"},
{"ji'e", "BAI", "up to limit", "jimte modal, 1st placelimitedly; up to limit ..."},
{"ji'i", "PA4", "approximately", "digit/number: approximately (default the typical value in this context) (number)"},
{"ji'o", "BAI", "under direction of", "jitro modal, 1st place (control)controlledly; under direction of ..."},
{"ji'u", "BAI", "based on", "jicmu modal, 1st place (assumptions);given that ...; based on ..."},
{"jo", "JA", "tanru iff", "logical connective: tanru-internal afterthought biconditional/iff/if-and-only-if"},
{"jo'a", "UI3a", "metalinguistic yes", "discursive: metalinguistic affirmer"},
{"jo'e", "JOI", "union", "non-logical connective: union of sets"},
{"jo'i", "JOhI", "array", "join mathematical expression (mex) operands into an array"},
{"jo'o", "BY1", "Arabic shift", "shift letterals to Arabic alphabet"},
{"jo'u", "JOI", "in common with", "non-logical connective: in common with; along with (unmixed)"},
{"joi", "JOI", "in a mass with", "non-logical connective: mixed conjunction; \"and\" meaning \"mixed together\", forming a mass"},
{"ju", "JA", "tanru whether", "logical connective: tanru-internal afterthought whether-or-not"},
{"ju'a", "UI2", "I state", "evidential: I state - (default) elliptical/non-specific basis"},
{"ju'e", "JOI", "vague connective", "vague non-logical connective: analogous to plain \".i\""},
{"ju'i", "COI", "attention", "vocative: attention - at ease - ignore me"},
{"ju'o", "UI5", "certainty", "attitudinal modifier: certainty - uncertainty - impossibility"},
{"ju'u", "VUhU2", "number base", "binary mathematical operator: number base; [a interpreted in the base b]"},
{"jy", "BY2", "j", "letteral for j"},
{"ka", "NU", "property abstract", "abstractor: property/quality abstractor (-ness); x1 is quality/property exhibited by [bridi]"},
{"ka'a", "BAI", "gone to by", "klama modal, 1st placegone to by ..."},
{"ka'e", "CAhA", "innately capable of", "modal aspect: innate capability; possibly unrealized"},
{"ka'i", "BAI", "represented by", "krati modal, 1st placerepresented by ..."},
{"ka'o", "PA5", "imaginary i", "digit/number: imaginary i; square root of -1"},
{"ka'u", "UI2", "I know culturally", "evidential: I know by cultural means (myth or custom)"},
{"kai", "BAI", "characterizing", "ckaji modal, 1st placecharacterizing ..."},
{"kau", "UI3a", "indirect question", "discursive: marks word serving as focus of indirect question: \"I know WHO went to the store\""},
{"ke", "KE", "start grouping", "start grouping of tanru, etc; ... type of ... ; overrides normal tanru left grouping"},
{"ke'a", "KOhA7", "relativized it", "pro-sumti: relativized sumti (object of relative clause)"},
{"ke'e", "KEhE", "end grouping", "elidable terminator: end of tanru left grouping override (usually elidable)"},
{"ke'i", "GAhO", "exclusive interval", "open interval bracket marker; modifies intervals in non-logical connectives; exclude boundaries"},
{"ke'o", "COI", "please repeat", "vocative: please repeat"},
{"ke'u", "UI3", "repeating", "discursive: repeating - continuing"},
{"kei", "KEI", "end abstraction", "elidable terminator: end abstraction bridi (often elidable)"},
{"ki", "KI", "tense default", "tense/modal: set/use tense default; establishes new open scope space/time/modal reference base"},
{"ki'a", "UI6", "textual confusion", "attitudinal question: confusion about something said"},
{"ki'e", "COI", "thanks", "vocative: thanks - no thanks to you"},
{"ki'i", "BAI", "as a relation of", "ckini modal, 1st place (related to)relatively; as a relation of ..."},
{"ki'o", "PA3", "number comma", "digit/number: number comma; thousands"},
{"ki'u", "BAI", "because of reason", "krinu modal, 1st place (justified by)justifiably; because of reason ..."},
{"ko", "KOhA3", "imperative", "pro-sumti: you (imperative); make it true for you, the listener"},
{"ko'a", "KOhA4", "it-1", "pro-sumti: he/she/it/they #1 (specified by goi)"},
{"ko'e", "KOhA4", "it-2", "pro-sumti: he/she/it/they #2 (specified by goi)"},
{"ko'i", "KOhA4", "it-3", "pro-sumti: he/she/it/they #3 (specified by goi)"},
{"ko'o", "KOhA4", "it-4", "pro-sumti: he/she/it/they #4 (specified by goi)"},
{"ko'u", "KOhA4", "it-5", "pro-sumti: he/she/it/they #5 (specified by goi)"},
{"koi", "BAI", "bounded by", "korbi modal, 1st place (bordered by)bounded by ..."},
{"ku", "KU", "end sumti", "elidable terminator: end description, modal, or negator sumti; often elidable"},
{"ku'a", "JOI", "intersection", "non-logical connective: intersection of sets"},
{"ku'e", "KUhE", "end mex forethought", "elidable terminator: end mathematical (mex) forethought (Polish) expression; often elidable"},
{"ku'i", "UI3b", "however", "discursive: however/but/in contrast"},
{"ku'o", "KUhO", "end relative clause", "elidable terminator: end NOI relative clause; always elidable, but preferred in complex clauses"},
{"ku'u", "BAI", "in culture", "kulnu modal, 1st placein culture ..."},
{"ky", "BY2", "k", "letteral for k"},
{"la", "LA", "that named", "name descriptor: the one(s) called ... ; takes name or selbri description"},
{"la'a", "UI3", "probability", "discursive: probability - improbability"},
{"la'e", "LAhE", "the referent of", "the referent of (indirect pointer); uses the referent of a sumti as the desired sumti"},
{"la'i", "LA", "the set of named", "name descriptor: the set of those named ... ; takes name or selbri description"},
{"la'o", "ZOI", "the non-Lojban named", "delimited non-Lojban name; the resulting quote sumti is treated as a name"},
{"la'u", "BAI", "quantifying", "klani modal, 1st place (amount)quantifying ...; being a quantity of ..."},
{"lai", "LA", "the mass of named", "name descriptor: the mass of individual(s) named ... ; takes name or selbri description"},
{"lau", "LAU", "punctuation mark", "2-word letteral/shift: punctuation mark or special symbol follows"},
{"le", "LE", "the described", "non-veridical descriptor: the one(s) described as ..."},
{"le'a", "BAI", "in category", "klesi modal, 1st place (scalar set)in/of category ..."},
{"le'e", "LE", "the stereotypical", "non-veridical descriptor: the stereotype of those described as ..."},
{"le'i", "LE", "the set described", "non-veridical descriptor: the set of those described as ..., treated as a set"},
{"le'o", "UI5", "aggressive", "attitudinal modifier: aggressive - passive - defensive"},
{"le'u", "LEhU", "end error quote", "end quote of questionable or out-of-context text; not elidable"},
{"lei", "LE", "the mass described", "non-veridical descriptor: the mass of individual(s) described as ..."},
{"li", "LI", "the number", "the number/evaluated expression; convert number/operand/evaluated math expression to sumti"},
{"li'a", "UI3", "clearly", "discursive: clearly - obscurely"},
{"li'e", "BAI", "preceded by", "lidne modal, 1st placepreceded by ...; non-time sequencing"},
{"li'i", "NU", "experience abstract", "abstractor: experience abstractor; x1 is x2's experience of [bridi] (participant or observer)"},
{"li'o", "UI3a", "omitted text", "discursive: omitted text (quoted material)"},
{"li'u", "LIhU", "end quote", "elidable terminator: end grammatical quotation; seldom elidable except at end of text"},
{"lo", "LE", "the really is", "veridical descriptor: the one(s) that really is(are) ..."},
{"lo'a", "BY1", "Lojban shift", "shift letterals to Lojban (Roman) alphabet"},
{"lo'e", "LE", "the typical", "veridical descriptor: the typical one(s) who really is(are) ..."},
{"lo'i", "LE", "the set really is", "veridical descriptor: the set of those that really are ..., treated as a set"},
{"lo'o", "LOhO", "end mex sumti", "elidable terminator: end math express.(mex) sumti; end mex-to-sumti conversion; usually elidable"},
{"lo'u", "LOhU", "error quote", "start questionable/out-of-context quote; text should be Lojban words, but needn't be grammatical"},
{"loi", "LE", "the mass really is", "veridical descriptor: the mass of individual(s) that is(are) ..."},
{"lu", "LU", "quote", "start grammatical quotation; quoted text should be grammatical on its own"},
{"lu'a", "LAhE", "the individuals of", "the members of the set/components of the mass; converts another description type to individuals"},
{"lu'e", "LAhE", "the symbol for", "the symbol for (indirect discourse); uses the symbol/word(s) for a sumti as the desired sumti"},
{"lu'i", "LAhE", "the set composed of", "the set with members; converts another description type to a set of the members"},
{"lu'o", "LAhE", "the mass composed of", "the mass composed of; converts another description type to a mass composed of the members"},
{"lu'u", "LUhU", "end sumti qualifiers", "elidable terminator: end of sumti qualifiers; usually elidable except before a sumti"},
{"ly", "BY2", "l", "letteral for l"},
{"ma", "KOhA7", "sumti ?", "pro-sumti: sumti question (what/who/how/why/etc.); appropriately fill in sumti blank"},
{"ma'a", "KOhA3", "we with you", "pro-sumti: me/we the speaker(s)/author(s) & you the listener(s) & others unspecified"},
{"ma'e", "BAI", "material object", "marji modal, 1st placematerial in object/substance ..."},
{"ma'i", "BAI", "in reference frame", "manri modal, 1st place (by standard 2)in reference frame ..."},
{"ma'o", "MAhO", "operand to operator", "convert letteral string or other mathematical expression (mex) operand to mex operator"},
{"ma'u", "PA3", "positive number", "digit/number: plus sign; positive number; default any positive"},
{"mai", "MAI", "sentence ordinal", "utterance ordinal suffix; converts a number to an ordinal, such as an item or paragraph number"},
{"mau", "BAI", "exceeded by", "zmadu modal, 1st place (a greater)exceeded by ... ; usually a sumti modifier"},
{"me", "ME", "sumti to selbri", "convert sumti to selbri/tanru element; x1 is specific to [sumti] in aspect x2"},
{"me'a", "BAI", "undercut by", "mleca modal, 1st place (a lesser)undercut by ... ; usually a sumti modifier"},
{"me'e", "BAI", "with name", "cmene modal, 1st place (requires quote)with name ...; so-called ..."},
{"me'i", "PA3", "less than", "digit/number: less than"},
{"me'o", "LI", "the mex", "the mathematical expression (unevaluated); convert unevaluated mathematical expression to sumti"},
{"me'u", "MEhU", "end sumti to selbri", "elidable terminator: end sumti that was converted to selbri; usually elidable"},
{"mei", "MOI", "cardinal selbri", "convert number to cardinality selbri; x1 is the mass formed from set x2 whose n member(s) are x3"},
{"mi", "KOhA3", "me", "pro-sumti: me/we the speaker(s)/author(s); identified by self-vocative"},
{"mi'a", "KOhA3", "we, not you", "pro-sumti: me/we the speaker(s)/author(s) & others unspecified, but not you, the listener"},
{"mi'e", "COI", "self-introduction", "self vocative: self-introduction - denial of identity; identifies speaker"},
{"mi'i", "BIhI", "center-range", "non-logical interval connective: ordered components: ... center, ... range surrounding center"},
{"mi'o", "KOhA3", "me and you", "pro-sumti: me/we the speaker(s)/author(s) & you the listener(s)"},
{"mi'u", "UI3b", "ditto", "discursive: ditto"},
{"mo", "GOhA", "bridi ?", "pro-bridi: bridi/selbri/brivla question"},
{"mo'a", "PA4", "too few", "digit/number: too few; subjective"},
{"mo'e", "MOhE", "sumti to operand", "convert sumti to mex operand; sample use in story arithmetic: [3 apples] + [3 apples] = what"},
{"mo'i", "MOhI", "space motion", "mark motions in space-time"},
{"mo'o", "MAI", "section ordinal", "higher-order utterance ordinal suffix; converts a number to ordinal, usually a section/chapter"},
{"moi", "MOI", "ordinal selbri", "convert number to ordinal selbri; x1 is (n)th member of set x2 ordered by rule x3"},
{"mu", "PA1", "5", "digit/number: 5 (digit) [five]"},
{"mu'a", "UI3", "for example", "discursive: for example - omitting - end examples"},
{"mu'e", "NU1", "point-event abstract", "abstractor: achievement (event) abstractor; x1 is the event-as-a-point/achievement of [bridi]"},
{"mu'i", "BAI", "because of motive", "mukti modal, 1st placebecause of motive ..."},
{"mu'o", "COI", "over", "vocative: over (response OK) - more to come"},
{"mu'u", "BAI", "exemplified by", "mupli modal, 1st placeexemplified by ..."},
{"my", "BY2", "m", "letteral for m"},
{"na", "NA", "bridi negator", "bridi contradictory negator; scope is an entire bridi; logically negates in some cmavo compounds"},
{"na'a", "BY1", "cancel shifts", "cancel all letteral shifts"},
{"na'e", "NAhE", "scalar contrary", "contrary scalar negator: other than ...; not ...; a scale or set is implied"},
{"na'i", "UI3a", "metalinguistic not", "discursive: metalinguistic negator"},
{"na'o", "TAhE", "typically", "tense interval modifier: characteristically/typically; tense/modal; defaults as time tense"},
{"na'u", "NAhU", "selbri to operator", "convert selbri to mex operator; used to create less-used operators using le'avla, lujvo, etc."},
{"nai", "NAI", "negate last word", "attached to cmavo to negate them; various negation-related meanings"},
{"nau", "CUhE", "reference point", "tense: refers to current space/time reference absolutely"},
{"ne", "GOI", "incidental phrase", "non-restrictive relative phrase marker: which incidentally is associated with ..."},
{"ne'a", "FAhA3", "next to", "location tense relation/direction; approximating/next to ..."},
{"ne'i", "FAhA3", "within", "location tense relation/direction; within/inside of/into ..."},
{"ne'o", "VUhU3", "factorial", "unary mathematical operator: factorial; a!"},
{"ne'u", "FAhA1", "south of", "location tense relation/direction; south of"},
{"nei", "GOhA", "current bridi", "pro-bridi: repeats the current bridi"},
{"ni", "NU", "amount abstract", "abstractor: quantity/amount abstractor; x1 is quantity/amount of [bridi] measured on scale x2"},
{"ni'a", "FAhA2", "below", "location tense relation/direction; downwards/down from ..."},
{"ni'e", "NIhE", "selbri to operand", "convert selbri to mex operand; used to create new non-numerical quantifiers; e.g. \"herd\" of oxen"},
{"ni'i", "BAI", "because of logic", "nibli modal, 1st placelogically; logically because ..."},
{"ni'o", "NIhO", "new topic", "discursive: paragraph break; introduce new topic"},
{"ni'u", "PA3", "negative number", "digit/number: minus sign; negative number); default any negative"},
{"no", "PA1", "0", "digit/number: 0 (digit) [zero]"},
{"no'a", "GOhA", "next outer bridi", "pro-bridi: repeats the bridi in which this one is embedded"},
{"no'e", "NAhE", "scalar midpoint not", "midpoint scalar negator: neutral point between je'a and to'e; \"not really\""},
{"no'i", "NIhO", "old topic", "discursive: paragraph break; resume previous topic"},
{"no'o", "PA5", "typical value", "digit/number: typical/average value"},
{"no'u", "GOI", "incidental identity", "non-restrictive appositive phrase marker: which incidentally is the same thing as ..."},
{"noi", "NOI", "incidental clause", "non-restrictive relative clause; attaches subordinate bridi with incidental information"},
{"nu", "NU", "event abstract", "abstractor: generalized event abstractor; x1 is state/process/achievement/activity of [bridi]"},
{"nu'a", "NUhA", "operator to selbri", "convert mathematical expression (mex) operator to a selbri/tanru component"},
{"nu'e", "COI", "promise", "vocative: promise - promise release - un-promise"},
{"nu'i", "NUhI", "start fore termset", "start forethought termset construct; marks start of place structure set with logical connection"},
{"nu'o", "CAhA", "can but has not", "modal aspect: can but has not; unrealized potential"},
{"nu'u", "NUhU", "end fore termset", "elidable terminator: end forethought termset; usually elidable except with following sumti"},
{"ny", "BY2", "n", "letteral for n"},
{"o", "A", "sumti iff", "logical connective: sumti afterthought biconditional/iff/if-and-only-if"},
{"o'a", "UI1", "pride", "attitudinal: pride - modesty/humility - shame"},
{"o'e", "UI1", "closeness", "attitudinal: closeness - distance"},
{"o'i", "UI1", "caution", "attitudinal: caution - rashness"},
{"o'o", "UI1", "patience", "attitudinal: patience - mere tolerance - anger"},
{"o'u", "UI1", "relaxation", "attitudinal: relaxation - composure - stress"},
{"oi", "UI1", "complaint", "attitudinal: complaint - pleasure"},
{"pa", "PA1", "1", "digit/number: 1 (digit) [one]"},
{"pa'a", "BAI", "in addition to", "panra modal, 1st place (parallel; shared property) similarly; in addition to ..."},
{"pa'e", "UI3", "justice", "discursive: justice - prejudice"},
{"pa'i", "VUhU2", "ratio", "binary mathematical operator: ratio; [the ratio of a to b]"},
{"pa'o", "FAhA3", "transfixing", "location tense relation/direction; transfixing/passing through ..."},
{"pa'u", "BAI", "having component", "pagbu modal, 1st placehaving component ..."},
{"pai", "PA5", "pi", "digit/number: pi (approximately 3.1416...)"},
{"pau", "UI3a", "question follows", "discursive: optional question premarker"},
{"pe", "GOI", "restrictive phrase", "restrictive relative phrase marker: which is associated with ...; loosest associative/possessive"},
{"pe'a", "UI3c", "figurative", "marks a construct as figurative (non-literal/metaphorical) speech/text"},
{"pe'e", "PEhE", "termset conn mark", "marks the following connective as joining termsets"},
{"pe'i", "UI2", "I opine", "evidential: I opine (subjective claim)"},
{"pe'o", "PEhO", "fore mex operator", "forethought flag for mathematical expression (mex) Polish (forethought) operator"},
{"pe'u", "COI", "please", "vocative: please"},
{"pei", "CAI", "emotion ?", "attitudinal: attitudinal question; how do you feel about it? with what intensity?"},
{"pi", "PA3", "decimal point", "digit/number: radix (number base) point; default decimal"},
{"pi'a", "VUhU4", "matrix of rows", "n-ary mathematical operator: operands are vectors to be treated as matrix rows"},
{"pi'e", "PA3", "digit separator", "digit/number:separates digits for base >16, not current standard, or variable (e.g. time, date)"},
{"pi'i", "VUhU1", "times", "n-ary mathematical operator: times; multiplication operator; [(((a * b) * c) * ...)]"},
{"pi'o", "BAI", "used by", "pilno modal, 1st placeused by ..."},
{"pi'u", "JOI", "cross product", "non-logical connective: cross product; Cartesian product of sets"},
{"po", "GOI", "is specific to", "restrictive relative phrase marker: which is specific to ...; normal possessive physical/legal"},
{"po'e", "GOI", "which belongs to", "restrictive relative phrase marker: which belongs to ... ; inalienable possession"},
{"po'i", "BAI", "in the sequence", "porsi modal, 1st place (in order)sequentially; in the sequence ..."},
{"po'o", "UI3b", "uniquely", "discursive: uniquely, only, solely: the only relevant case"},
{"po'u", "GOI", "restrictive identity", "restrictive appositive phrase marker: which is the same thing as"},
{"poi", "NOI", "restrictive clause", "restrictive relative clause; attaches subordinate bridi with identifying information to a sumti"},
{"pu", "PU", "before", "time tense relation/direction: did [selbri]; before/prior to [sumti]; default past tense"},
{"pu'a", "BAI", "pleased by", "pluka modal, 1st placepleased by ..."},
{"pu'e", "BAI", "by process", "pruce modal, 1st place (in manner 1)by process ..."},
{"pu'i", "CAhA", "can and has", "modal aspect: can and has; demonstrated potential"},
{"pu'u", "NU1", "process abstract", "abstractor: process (event) abstractor; x1 is process of [bridi] proceeding in stages x2"},
{"py", "BY2", "p", "letteral for p"},
{"ra", "KOhA5", "recent sumti", "pro-sumti: a recent sumti before the last one, as determined by back-counting rules"},
{"ra'a", "BAI", "pertained to by", "srana modal, 1st placepertained to by ... (generally more specific)"},
{"ra'e", "PA3", "repeating decimal", "digit/number: repeating digits (of a decimal) follow"},
{"ra'i", "BAI", "from source", "krasi modal, 1st placefrom source/origin/starting point ..."},
{"ra'o", "RAhO", "pro-assign update", "flag GOhA to indicate pro-assignment context updating for all pro-assigns in referenced bridi"},
{"ra'u", "UI3", "chiefly", "discursive: chiefly - equally - incidentally"},
{"rai", "BAI", "with superlative", "traji modal, 1st placewith superlative ..."},
{"rau", "PA4", "enough", "digit/number: enough; subjective"},
{"re", "PA1", "2", "digit/number: 2 (digit) [two]"},
{"re'a", "VUhU4", "transpose", "unary mathematical operator: matrix transpose/dual; A*"},
{"re'e", "UI4", "spiritual", "emotion category/modifier: religious/spiritual/worship - sacrilege"},
{"re'i", "COI", "ready to receive", "vocative: ready to receive - not ready to receive"},
{"re'o", "FAhA3", "adjacent to", "location tense relation/direction; adjacent to/touching/contacting ..."},
{"re'u", "ROI", "ordinal tense", "converts number to an objectively quantified ordinal tense interval modifier; defaults to time"},
{"rei", "PA2", "hex digit E", "digit/number: hex digit E (decimal 14) [fourteen]"},
{"ri", "KOhA5", "last sumti", "pro-sumti: the last sumti, as determined by back-counting rules"},
{"ri'a", "BAI", "because of cause", "rinka modal, 1st place (phys./mental)causal because ..."},
{"ri'e", "UI5", "release of emotion", "attitudinal modifier: release of emotion - emotion restraint"},
{"ri'i", "BAI", "experienced by", "lifri modal, 1st place patient/passive case tag; happens to...,experienced by...,with passive..."},
{"ri'o", "VUhU4", "integral", "trinary mathematical operator: [integral of a with respect to b over range c]"},
{"ri'u", "FAhA2", "on the right of", "location tense relation/direction; rightwards/to the right of ..."},
{"ro", "PA4", "each", "digit/number: each, all"},
{"ro'a", "UI4", "social", "emotion category/modifier: social - antisocial"},
{"ro'e", "UI4", "mental", "emotion category/modifier: mental - mindless"},
{"ro'i", "UI4", "emotional", "emotion category/modifier: emotional - denying emotion"},
{"ro'o", "UI4", "physical", "emotion category/modifier: physical - denying physical"},
{"ro'u", "UI4", "sexual", "emotion category/modifier: sexual - sexual abstinence"},
{"roi", "ROI", "quantified tense", "converts number to an objectively quantified tense interval modifier; defaults to time tense"},
{"ru", "KOhA5", "earlier sumti", "pro-sumti: a remote past sumti, before all other in-use backcounting sumti"},
{"ru'a", "UI2", "I postulate", "evidential: I postulate"},
{"ru'e", "CAI", "weak emotion", "attitudinal: weak intensity attitude modifier"},
{"ru'i", "TAhE", "continuously", "tense interval modifier: continuously; subjective tense/modal; defaults as time tense"},
{"ru'o", "BY1", "Cyrillic shift", "shift letterals to Cyrillic alphabet"},
{"ru'u", "FAhA2", "surrounding", "location tense relation/direction; surrounding/annular ..."},
{"ry", "BY2", "r", "letteral for r"},
{"sa", "SA", "erase utterance", "erase complete or partial utterance; next word shows how much erasing to do"},
{"sa'a", "UI3a", "editorial insertion", "discursive: material inserted by editor/narrator (bracketed text)"},
{"sa'e", "UI3", "precisely speaking", "discursive: precisely speaking - loosely speaking"},
{"sa'i", "VUhU4", "matrix of columns", "n-ary mathematical operator: operands are vectors to be treated as matrix columns"},
{"sa'o", "VUhU4", "derivative", "trinary mathematical operator: [derivative of a with respect to b of degree c]"},
{"sa'u", "UI3", "simply speaking", "discursive: simply - elaborating"},
{"sai", "CAI", "strong emotion", "attitudinal: moderate intensity attitude modifier"},
{"sau", "BAI", "requiring", "sarcu modal, 1st placerequiring ..."},
{"se", "SE", "2nd conversion", "2nd conversion; switch 1st/2nd places"},
{"se'a", "UI5", "self-sufficiency", "attitudinal modifier: self-sufficiency - dependency"},
{"se'e", "BY1", "character code", "following digits code a character (in ASCII, Unicode, etc.)"},
{"se'i", "UI5", "self-oriented", "attitudinal modifier: self-oriented - other-oriented"},
{"se'o", "UI2", "I know internally", "evidential: I know by internal experience (dream, vision, or personal revelation)"},
{"se'u", "SEhU", "end discursive", "elidable terminator: end discursive bridi or mathematical precedence;usually elidable"},
{"sei", "SEI", "discursive bridi", "start discursive (metalinguistic) bridi"},
{"si", "SI", "erase word", "erase the last Lojban word, treating non-Lojban text as a single word"},
{"si'a", "UI3b", "similarly", "discursive: similarly"},
{"si'e", "MOI", "portion selbri", "convert number to portion selbri; x1 is an (n)th portion of mass/totality x2; (cf. gunma)"},
{"si'i", "VUhU4", "sigma summation", "trinary mathematical operator: [sigma summation of a using variable b over range c]"},
{"si'o", "NU", "concept abstract", "abstractor: idea/concept abstractor; x1 is x2's concept of [bridi]"},
{"si'u", "BAI", "aided by", "sidju modal, 1st place (aiding agent)aided by ..."},
{"so", "PA1", "9", "digit/number: 9 (digit) [nine]"},
{"so'a", "PA4", "almost all", "digit/number: almost all (digit/number)"},
{"so'e", "PA4", "most", "digit/number: most"},
{"so'i", "PA4", "many", "digit/number: many"},
{"so'o", "PA4", "several", "digit/number: several"},
{"so'u", "PA4", "few", "digit/number: few"},
{"soi", "SOI", "reciprocal sumti", "discursive: reciprocal sumti marker; indicates a reciprocal relationship between sumti"},
{"su", "SU", "erase discourse", "erase to start of discourse or text; drop subject or start over"},
{"su'a", "UI2", "I generalize", "evidential: I generalize - I particularize; discursive: abstractly - concretely"},
{"su'e", "PA4", "at most", "digit/number: at most (all); no more than"},
{"su'i", "VUhU1", "plus", "n-ary mathematical operator: plus; addition operator; [(((a + b) + c) + ...)]"},
{"su'o", "PA4", "at least", "digit/number: at least (some); no less than"},
{"su'u", "NU", "unspecif abstract", "abstractor: generalized abstractor (how); x1 is [bridi] as a non-specific abstraction of type x2"},
{"sy", "BY2", "s", "letteral for s"},
{"ta", "KOhA6", "that there", "pro-sumti: that there; nearby demonstrative it; indicated thing/place near listener"},
{"ta'a", "COI", "interruption", "vocative: interruption"},
{"ta'e", "TAhE", "habitually", "tense interval modifier: habitually; subjective tense/modal; defaults as time tense"},
{"ta'i", "BAI", "by method", "tadji modal, 1st place (in manner 3)methodically; by method ..."},
{"ta'o", "UI3", "by the way", "discursive: by the way - returning to main point"},
{"ta'u", "UI3a", "making a tanru", "discursive: making a tanru - expanding the tanru"},
{"tai", "BAI", "in form", "tamsmi modal, 1st place (like)/(in manner 2)resembling ...; sharing ideal form ..."},
{"tau", "LAU", "shift next lerfu", "2-word letteral/shift: change case for next letteral only"},
{"te", "SE", "3rd conversion", "3rd conversion; switch 1st/3rd places"},
{"te'a", "VUhU2", "to the power", "binary mathematical operator: to the power; exponential; [a to the b power]"},
{"te'e", "FAhA3", "bordering", "location tense relation/direction; edged by/edging up to ..."},
{"te'o", "PA5", "exponential e", "digit/number: exponential e (approx 2.71828...)"},
{"te'u", "TEhU", "end mex converters", "elidable terminator: end conversion between non-mex and mex; usually elidable"},
{"tei", "TEI", "composite lerfu", "composite letteral follows; used for muti-character letterals"},
{"ti", "KOhA6", "this here", "pro-sumti: this here; immediate demonstrative it; indicated thing/place near speaker"},
{"ti'a", "FAhA2", "behind", "location tense relation/direction; rearwards/to the rear of ..."},
{"ti'e", "UI2", "I hear", "evidential: I hear (hearsay)"},
{"ti'i", "BAI", "suggested by", "stidi modal, 1st placesuggested by ...; proposed by ..."},
{"ti'o", "SEI", "mex precedence", "mathematical expression (mex) operator precedence (discursive)"},
{"ti'u", "BAI", "associated with time", "tcika modal, 1st place (for letters)associated with time ... ; attach time stamp"},
{"to", "TO", "start parenthesis", "left parenthesis; start of parenthetical note which must be grammatical Lojban text"},
{"to'a", "BY1", "lower-case shift", "lower-case letteral shift"},
{"to'e", "NAhE", "polar opposite", "polar opposite scalar negator"},
{"to'i", "TO", "editorial unquote", "open editorial unquote (within a quote); contains grammatical text; mark with editorial insert"},
{"to'o", "FAhA4", "away from point", "location tense relation/direction; departing from/directly away from ..."},
{"to'u", "UI3", "in brief", "discursive: in brief - in detail"},
{"toi", "TOI", "end parenthesis", "elidable terminator: right parenthesis/end unquote; seldom elidable except at end of text"},
{"tu", "KOhA6", "that yonder", "pro-sumti: that yonder; distant demonstrative it; indicated thing far from speaker&listener"},
{"tu'a", "LAhE", "the bridi implied by", "extracts a concrete sumti from an unspecified abstraction; equivalent to le nu/su'u [sumti] co'e"},
{"tu'e", "TUhE", "start text scope", "start of multiple utterance scope; used for logical/non-logical/ordinal joining of sentences"},
{"tu'i", "BAI", "associated with site", "stuzi modal, 1st place (used to situate letters)associated with site ... ; label with location"},
{"tu'o", "PA5", "null operand", "digit/number: null operand (used in unary operations); a non-specific/elliptical number"},
{"tu'u", "TUhU", "end text scope", "elidable terminator: end multiple utterance scope; seldom elidable"},
{"ty", "BY2", "t", "letteral for t"},
{"u", "A", "sumti whether", "logical connective: sumti afterthought whether-or-not"},
{"u'a", "UI1", "gain", "attitudinal: gain - loss"},
{"u'e", "UI1", "wonder", "attitudinal: wonder - commonplace"},
{"u'i", "UI1", "amusement", "attitudinal: amusement - weariness"},
{"u'o", "UI1", "courage", "attitudinal: courage - timidity - cowardice"},
{"u'u", "UI1", "repentance", "attitudinal: repentance - lack of regret - innocence"},
{"ua", "UI1", "discovery", "attitudinal: discovery - confusion/searching"},
{"ue", "UI1", "surprise", "attitudinal: surprise - not really surprised - expectation"},
{"ui", "UI1", "happiness", "attitudinal: happiness - unhappiness"},
{"uo", "UI1", "completion", "attitudinal: completion - incompleteness"},
{"uu", "UI1", "pity", "attitudinal: pity - cruelty"},
{"va", "VA", "there at", "location tense distance: near to ... ; there at ...; a medium/small distance from ..."},
{"va'a", "VUhU3", "additive inverse", "unary mathematical operator: additive inverse; [- a]"},
{"va'e", "MOI", "scalar selbri", "convert number to scalar selbri; x1 is at (n)th position on scale x2"},
{"va'i", "UI3", "in other words", "discursive: in other words - in the same words"},
{"va'o", "BAI", "under conditions", "vanbi modal, 1st place (conditions 1)under conditions ...; in environment ..."},
{"va'u", "BAI", "benefiting from", "xamgu modal, 1st place beneficiary case tag complementbenefiting from ..."},
{"vai", "PA2", "hex digit F", "digit/number: hex digit F (decimal 15) [fifteen]"},
{"vau", "VAU", "end simple bridi", "elidable: end of sumti in simple bridi; in compound bridi, separates common trailing sumti"},
{"ve", "SE", "4th conversion", "4th conversion; switch 1st/4th places"},
{"ve'a", "VEhA", "small space interval", "location tense interval: a small/medium region of space"},
{"ve'e", "VEhA", "whole space interval", "location tense interval: the whole of space"},
{"ve'i", "VEhA", "tiny space interval", "location tense interval: a tiny region of space"},
{"ve'o", "VEhO", "right bracket", "right mathematical bracket"},
{"ve'u", "VEhA", "big space interval", "location tense interval: a large region of space"},
{"vei", "VEI", "left bracket", "left mathematical bracket"},
{"vi", "VA", "here at", "location tense distance: here at ... ; at or a very short/tiny distance from ..."},
{"vi'a", "VIhA", "2-space interval", "dimensionality of space interval tense: 2-space interval; throughout an area"},
{"vi'e", "VIhA", "4-space interval", "dimensionality of space interval tense: 4-space interval; throughout a spacetime"},
{"vi'i", "VIhA", "1-space interval", "dimensionality of space interval tense: 1-space interval; along a line"},
{"vi'o", "COI", "wilco", "vocative: wilco (ack and will comply)"},
{"vi'u", "VIhA", "3-space interval", "dimensionality of space interval tense: 3-space interval; throughout a space"},
{"vo", "PA1", "4", "digit/number: 4 (digit) [four]"},
{"vo'a", "KOhA4", "x1 it", "pro-sumti: repeats 1st place of main bridi of this sentence"},
{"vo'e", "KOhA4", "x2 it", "pro-sumti: repeats 2nd place of main bridi of this sentence"},
{"vo'i", "KOhA4", "x3 it", "pro-sumti: repeats 3rd place of main bridi of this sentence"},
{"vo'o", "KOhA4", "x4 it", "pro-sumti: repeats 4th place of main bridi of this sentence"},
{"vo'u", "KOhA4", "x5 it", "pro-sumti: repeats 5th place of main bridi of this sentence"},
{"voi", "NOI", "descriptive clause", "non-veridical restrictive clause used to form complicated le-like descriptions using \"ke'a\""},
{"vu", "VA", "yonder at", "location tense distance: far from ... ; yonder at ... ; a long distance from ..."},
{"vu'a", "FAhA1", "west of", "location tense relation/direction; west of"},
{"vu'e", "UI5", "virtue", "attitudinal modifier: virtue - sin"},
{"vu'i", "LAhE", "the sequence of", "sumti qualifier: the sequence made from set or composed of elements/components; order is vague"},
{"vu'o", "VUhO", "long scope relative", "joins relative clause/phrase to complete complex or logically connected sumti in afterthought"},
{"vu'u", "VUhU1", "minus", "n-ary mathematical operator: minus; subtraction operator; [(((a - b) - c) - ...)]"},
{"vy", "BY2", "v", "letteral for v"},
{"xa", "PA1", "6", "digit/number: 6 (digit) [six]"},
{"xe", "SE", "5th conversion", "5th conversion; switch 1st/5th places"},
{"xi", "XI", "subscript", "subscript; attaches a numer of letteral string following as a subscript onto grammar structures"},
{"xo", "PA5", "number ?", "digit/number: number/digit/lerfu question"},
{"xu", "UI6", "true-false ?", "discursive: true-false question"},
{"xy", "BY2", "x", "letteral for x"},
{"y", "Y", "hesitation", "hesitation noise; maintains the floor while speaker decides what to say next"},
{"y'y", "BY2", "'", "letteral for '"},
{"za", "ZI", "medium time", "time tense distance: medium distance in time"},
{"za'a", "UI2", "I observe", "evidential: I observe"},
{"za'e", "BAhE", "nonce-word next", "forethought nonce-word indicator; indicates next word is nonce-creation and may be nonstandard"},
{"za'i", "NU1", "state abstract", "abstractor: state (event) abstractor; x1 is continuous state of [bridi] being true"},
{"za'u", "PA3", "greater than", "digit/number: greater than"},
{"zai", "LAU", "select alphabet", "2-word letteral/shift: alternate alphabet selector follows"},
{"zau", "BAI", "approved by", "zanru modal, 1st placeapproved by ..."},
{"ze", "PA1", "7", "digit/number: 7 (digit) [seven]"},
{"ze'a", "ZEhA", "medium time interval", "time tense interval: a medium length of time"},
{"ze'e", "ZEhA", "whole time interval", "time tense interval: the whole of time"},
{"ze'i", "ZEhA", "short time interval", "time tense interval: an instantaneous/tiny/short amount of time"},
{"ze'o", "FAhA4", "outward", "location tense relation/direction; beyond/outward/receding from ..."},
{"ze'u", "ZEhA", "long time interval", "time tense interval: a long amount of time"},
{"zei", "ZEI", "lujvo glue", "joins preceding and following words into a lujvo"},
{"zi", "ZI", "short time", "time tense distance: instantaneous-to-short distance in time"},
{"zi'e", "ZIhE", "rel clause joiner", "joins relative clauses which apply to the same sumti"},
{"zi'o", "KOhA7", "nonexistent it", "pro-sumti: fills a sumti place, deleting it from selbri place structure;changes selbri semantics"},
{"zo", "ZO", "1-word quote", "quote next word only; quotes a single Lojban word (not a cmavo compound or tanru)"},
{"zo'a", "FAhA4", "tangential to", "location tense relation/direction; tangential to/passing by ..."},
{"zo'e", "KOhA7", "unspecif it", "pro-sumti: an elliptical/unspecified value; has some value which makes bridi true"},
{"zo'i", "FAhA4", "inward", "location tense relation/direction; nearer than .../inward/approaching from ..."},
{"zo'o", "UI5", "humorously", "attitudinal modifier: humorously - dully - seriously"},
{"zo'u", "ZOhU", "end prenex", "marks end of logical prenex quantifiers/topic identification and start of sentence bridi"},
{"zoi", "ZOI", "non-Lojban quote", "delimited non-Lojban quotation; the result treated as a block of text"},
{"zu", "ZI", "long time", "time tense distance: long distance in time"},
{"zu'a", "FAhA2", "on the left of", "location tense relation/direction; leftwards/to the left of ..."},
{"zu'e", "BAI", "with actor", "zukte modal, 1st place (purposed agent)with goal-seeking actor ..."},
{"zu'i", "KOhA7", "typical it", "pro-sumti: the typical sumti value for this place in this relationship; affects truth value"},
{"zu'o", "NU1", "activity abstract", "abstractor: activity (event) abstractor; x1 is abstract activity of [bridi] composed of x2"},
{"zu'u", "UI3", "on the one hand", "discursive: on the one hand - on the other hand"},
{"zy", "BY2", "z", "letteral for z"},
{"ba'o", "ZAhO", "perfective", "interval event contour: in the aftermath of ...; since ...; perfective  |     |----"},
{"ca'o", "ZAhO", "continuative", "interval event contour: during ...; continuative  |-----|"},
{"co'a", "ZAhO", "initiative", "interval event contour: at the starting point of ...; initiative  >|<    |"},
{"co'i", "ZAhO", "achievative ", "interval event contour: at the instantaneous point of ...; achievative; point event  >|<"},
{"co'u", "ZAhO", "cessative", "interval event contour: at the ending point of ... even if not done; cessative  |  >< |"},
{"de'a", "ZAhO", "pausative", "event contour for a temporary halt and ensuing pause in a process"},
{"di'a", "ZAhO", "resumptitive", "event contour for resumption of a paused process"},
{"mo'u", "ZAhO", "completive", "interval event contour: at the natural ending point of ...; completive  |    >|<"},
{"pu'o", "ZAhO", "anticipative", "interval event contour: in anticipation of ...;  until ... ; inchoative  ----|     |"},
{"za'o", "ZAhO", "superfective", "interval event contour: continuing too long after natural end of ...; superfective  |   ---->"},
};
